services:
  db:
    image: mysql:8.0.33
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "backend"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --explicit-defaults-for-timestamp=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    hostname: redis
    volumes:
      - ../redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"